In [25]:
import pandas as pd

In [27]:
usps_columns = ['State','PHYSICAL CITY', 'PHYSICAL ZIP','PHYSICAL DELV ADDR']

df_usps = pd.read_csv('../public/dataset/usps_zip.csv', usecols = usps_columns)

df_usps.rename(columns={
    'PHYSICAL CITY': 'city',
    'State': 'state',
    'PHYSICAL ZIP': 'zip',
    'PHYSICAL DELV ADDR': 'address'
}, inplace=True)

df_usps

,address,city,zip,state
0,37 CALLE MUNOZ RIVERA,ADJUNTAS,601,Puerto Rico
1,9846 ESTATE THOMAS,ST THOMAS,802,U.S. Virgin Islands
2,600 SUFFIELD ST,AGAWAM,1001,Massachusetts
3,70A CRANDALL RD,ADAMSVILLE,2801,Rhode Island
4,199 STATE ROUTE 101 UNIT 4D,AMHERST,3031,New Hampshire
5,43 ROUTE 236,BERWICK,3901,Maine
6,27 S MAIN ST,WHITE RIVER JUNCTION,5001,Vermont
7,15 ENFORD ST,AVON,6001,Connecticut
8,1 ORIENTAL AVE,FISHERS ISLAND,6390,New York
9,1065 RAHWAY AVE,AVENEL,7001,New Jersey
10,517 FRANKLIN AVE,ALIQUIPPA,15001,Pennsylvania
11,125 RICKEY BLVD,BEAR,19701,Delaware
12,114 HALLTOWN RD,MARYDEL,21649,Maryland
13,416 FLORIDA AVE NW,WASHINGTON,20001,District of Columbia
14,45005 AVIATION DR STE 120,STERLING,20166,Virginia
15,11331 SWEET SPRINGS VALLEY RD,GAP MILLS,24941,West Virginia
16,1860 NC HIGHWAY 801 S,ADVANCE,27006,North Carolina
17,1842 MAIN ST,ALCOLU,29001,South Carolina
18,15 FRANKLIN ST,AVONDALE ESTATES,30002,Georgia
19,824 SCENIC HWY,LOOKOUT MOUNTAIN,37350,Tennessee
20,225 COLLEGE DR,ORANGE PARK,32065,Florida
21,2455 MOODY PKWY,MOODY,35004,Alabama
22,416 WALNUT ST,FULTON,42041,Kentucky
23,8 E LONG ST,ABBEVILLE,38601,Mississippi
24,2 W MAIN ST,ALEXANDRIA,43001,Ohio
25,102 W PEARL ST,UNION CITY,47390,Indiana
26,801 SAINT CLAIR RIVER DR,ALGONAC,48001,Michigan
27,105 MAIN ST,MILO,50166,Iowa
28,3030 MEREDITH AVE,OMAHA,68111,Nebraska
29,611 MAINE AVE,ADELL,53001,Wisconsin
30,3121 SAINT CROIX TRL S,AFTON,55001,Minnesota
31,926 2ND AVE N,WAHPETON,58075,North Dakota
32,111 DAKOTA ST,ALCESTER,57001,South Dakota
33,25 N MONTANA AVE,ABSAROKEE,59001,Montana
34,420 ORCHARD ST,ANTIOCH,60002,Illinois
35,16105 SWINGLEY RIDGE RD,CHESTERFIELD,63017,Missouri
36,621 KANSAS AVE,ATCHISON,66002,Kansas
37,3517 JOHNSON ST,METAIRIE,70001,Louisiana
38,100 E 8TH AVE STE 105,PINE BLUFF,71601,Arkansas
39,2211 N ROBISON RD,TEXARKANA,75501,Texas
40,22180 STATE HIGHWAY 146,ALBERT,73001,Oklahoma
41,1190 ANTHONY DR,ANTHONY,88021,New Mexico
42,5885 ALLISON ST,ARVADA,80004,Colorado
43,4800 CONVERSE AVE,CHEYENNE,82009,Wyoming
44,730 E CLARK ST,POCATELLO,83201,Idaho
45,100 N WASHINGTON AVE,NEWPORT,99156,Washington
46,15537 W 4000 N,ALTAMONT,84001,Utah
47,85 S CENTRAL ST,COLORADO CITY,86021,Arizona
48,40 N PURPLE SAGE AVE,ALAMO,89001,Nevada
49,7101 S CENTRAL AVE,LOS ANGELES,90001,California
50,99-040 KAUHALE ST,AIEA,96701,Hawaii
51,1 LUMANAI BLDG,PAGO PAGO,96799,American Samoa
52,489 ARMY DR,BARRIGADA,96913,Guam
53,1 PALAU,KOROR,96940,Palau
54,1 KOLONIA TOWN,POHNPEI,96941,Federated States of Micronesia
55,1 CAPITOL HL,SAIPAN,96950,Northern Mariana Islands
56,1 ULIGA TOWN,MAJURO,96960,Marshall Islands
57,45404 MAIN ST,ANTELOPE,97001,Oregon
58,800 INGRA ST,ANCHORAGE,99501,Alaska

In [50]:
campaigns_columns = ['event_id','state', 'event_type','begin_date_time','episode_title','episode_narrative','event_narrative','cz_name']

df_campaigns = pd.read_csv('../public/dataset/details_c.csv', usecols = campaigns_columns)

df_campaigns

,event_id,state,event_type,cz_name,begin_date_time,episode_title,episode_narrative,event_narrative
0,963885,GULF OF MEXICO,Waterspout,TAMPA BAY,07/21/2021 07:27:00,07/21 - Morning shower spawns waterspout over ...,Waterspout formed over Tampa Bay in associatio...,Broadcast media relayed images and video share...
1,963893,GULF OF MEXICO,Marine Thunderstorm Wind,TAMPA BAY,07/12/2021 14:32:00,07/12 - Afternoon storms produce strong marine...,Afternoon convection moving over Tampa Bay are...,ASOS site KPIE St. Petersburg-Clearwater Inter...
2,963895,GULF OF MEXICO,Marine Thunderstorm Wind,TAMPA BAY,07/12/2021 14:31:00,07/12 - Afternoon storms produce strong marine...,Afternoon convection moving over Tampa Bay are...,ASOS site KTPA Tampa International Airport rep...
3,963897,GULF OF MEXICO,Marine Thunderstorm Wind,ENGLEWOOD TO TARPON SPRINGS FL OUT 20NM,07/12/2021 14:54:00,07/12 - Afternoon storms produce strong marine...,Afternoon convection moving over Tampa Bay are...,Mesonet site near Clearwater Beach reported a ...
4,963898,GULF OF MEXICO,Marine Thunderstorm Wind,TAMPA BAY,07/12/2021 14:28:00,07/12 - Afternoon storms produce strong marine...,Afternoon convection moving over Tampa Bay are...,AWOS site KMCF MacDill Air Force Base reported...
...,...,...,...,...,...,...,...,...
7637,979300,NEW YORK,Tropical Storm,SOUTHERN NASSAU,07/09/2021 05:00:00,7/8-9/2021 Tropical Storm Elsa Impacts Southea...,Tropical Storm Elsa with maximum sustained win...,A mesonet station at Jones Beach NY recorded a...
7638,977732,CONNECTICUT,Tropical Storm,NORTHERN NEW LONDON,07/09/2021 05:00:00,7/9/2021 Tropical Storm Elsa Impacts Southern ...,Tropical Storm Elsa with maximum sustained win...,The highest sustained winds generally measured...
7639,979309,NEW YORK,Tropical Storm,SOUTHEAST SUFFOLK,07/09/2021 05:00:00,7/8-9/2021 Tropical Storm Elsa Impacts Southea...,Tropical Storm Elsa with maximum sustained win...,The Shinnecock Light NY mesonet recorded a max...
7640,979311,NEW YORK,Tropical Storm,NORTHEAST SUFFOLK,07/09/2021 05:00:00,7/8-9/2021 Tropical Storm Elsa Impacts Southea...,Tropical Storm Elsa with maximum sustained win...,The Baiting Hollow NY mesonet recorded a maxim...
7641,977439,ARIZONA,Flash Flood,MARICOPA,07/23/2021 14:10:00,Scattered storms produced damaging winds and f...,Strong to severe thunderstorms developed in an...,A streamflow gage on New River near Table Mesa...

In [58]:
water_events = ['Flood', 'Flash Flood','Coastal Flood', 'Heavy Rain', 'Storm Surge/Tide']
heat_events = ['Excessive Heat', 'Heat', 'Drought']
wind_events = ['High Wind', 'Strong Wind', 'Thunderstorm Wind', 'Dust Storm']
marine_events = ['Rip Current', 'High Surf', 'Marine Hail', 'Marine Thunderstorm Wind', 'Marine Tropical Depression', 'Marine Tropical Storm', 'Waterspout']
severe_weather_events = ['Hail', 'Lightning','Tornado', 'Funnel Cloud']
fire_events = ['Wildfire', 'Debris Flow']
tropical_cyclone_events = ['Tropical Depression', 'Tropical Storm']

In [56]:
for i, campaign in df_campaigns.iterrows():
    event_type = campaign["event_type"]
    main_event_type=''
    image_folder = ''
    if event_type in water_events:
        main_event_type = 'Flooding and Water-Related'
        image_folder = 'Water'
    elif event_type in heat_events:
        main_event_type = 'Heat and Drought'
        image_folder = 'Drought'
    elif event_type in wind_events:
        main_event_type = 'Wind and Storm'
        image_folder = 'Infrastructure'
    elif event_type in marine_events:
        main_event_type = 'Coastal and Marine'
        image_folder = 'Water'
    elif event_type in severe_weather_events:
        main_event_type = 'Severe Weather'
        image_folder = 'Infrastructure'
    elif event_type in fire_events:
        main_event_type = 'Fire and Land Instability
        image_folder = 'Wildfire
    elif event_type in tropical_cyclone_events:
        main_event_type = 'Tropical Cyclones'
        image_folder = 'Water'
    else:
        main_event_type = 'Other'